タイムテーブルにスピーカーを掲載
railsgirls-jp/gathering.railsgirls.jp pull request #23
Opened 2022-11-26 07:26 UTC by cobachie

![image](https://user-images.githubusercontent.com/7006340/204077435-6b4453a8-bbe2-4454-8318-0fc054845a67.png)

2022-11-26 09:40 UTC, hsbt commented on src/pages/index.js
> +            <span>なんで女性エンジニアが必要なのか(仮)</span><br />
```suggestion
            <span>Rails Girls から始めるエンジニアリングの世界</span><br />
```

2022-11-26 09:40 UTC, hsbt commented on src/pages/index.js
> +            <span>なんで女性エンジニアが必要なのか(仮)</span><br />
タイトルを仮ではなく入れました!

2022-11-26 09:57 UTC, cobachie commented on src/pages/index.js
> +            <span>なんで女性エンジニアが必要なのか(仮)</span><br />
ありがとうございます！

2022-11-26 15:56 UTC, attsumi commented on src/components/index.module.css
> +  padding-top: 0.75rem;
[want]
Lighting Talks の文字列と区別をする意図で色と太さを変えた意図かなと思ったのですが、使用してない色なので気になりました。
文字色は現状使用してる ` --color-text: #001858;`のままか、変えるとしても同色系統で濃淡を変えるが良さそうです。

[imo]
テーブルの他の情報よりも強調させたい意図がなければ weight も normal にして、テーブルの他部分の文字列を bold にした方が、情報の主従関係的にも自然かもです。

2022-11-26 16:05 UTC, attsumi requested changes

2022-11-26 16:05 UTC, attsumi commented on src/components/index.module.css
> +.timeTable td .lightningTalk {
```suggestion
.timeTable td .lightningTalk {
  font-size: 0.875rem;
  padding-top: 0.75rem;
}

```

2022-11-26 16:05 UTC, attsumi commented on src/components/index.module.css
> +.timeTable td .lightningTalk {
[want] Lighting Talks の文字列と区別をする意図で色と太さを変えた意図かなと思ったのですが、使用してない色なので少し目立ってしまうのが気になりました。 文字色は現状使用してる --color-text: #001858;のままか、もしくは同色系統で濃淡を変える（例.--color-text の透明度を変える）が良さそうです。

[imo] テーブルの他情報よりも強調させたい意図がなければ weight も normal にして、テーブル他情報の文字列 .timeTable td を bold にした方が、情報の主従関係的にも自然かもです。

2022-11-26 16:13 UTC, attsumi requested changes

2022-11-26 16:13 UTC, attsumi commented on src/pages/index.js
> +          <Link to="https://twitter.com/okuramasafumi" target="blank">大倉雅史</Link>
@cobachie 細かいのですが、苗字と名前の間に半角スペース挿入お願いします:pray:

2022-11-26 16:15 UTC, attsumi commented
@cobachie 
情報更新とスタイル調整ありがとうございます！！
何点かコメントしました、ご確認お願いいたします！

2022-11-27 00:05 UTC, cobachie commented on src/components/index.module.css
> +.timeTable td .lightningTalk {
ありがとうございます！勉強になる〜

いろいろ試して全部盛りにしちゃったのですが、
文字サイズを変えるだけでいい感じになる気がしたのでそうしました！どうでしょうか？ @attsumi 

![image](https://user-images.githubusercontent.com/7006340/204113462-9d47028e-f41a-4d2a-89e6-aea5bc8b9f4e.png)

2022-11-27 01:49 UTC, attsumi commented on src/components/index.module.css
> +.timeTable td .lightningTalk {
良さそう！色々試してくださりありがとうございます！！！

2022-11-27 01:50 UTC, attsumi approved these changes

2022-11-27 01:52 UTC, attsumi commented
対応ありがとうございます！！
approveしました！

2022-11-27 06:41 UTC, merged